/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DomainProduct.Drinks;
import java.awt.Color;
import static java.awt.Color.RED;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class SelectMenu extends DefaultFrame {

    /**
     * Creates new form SelectMenu
     */
    public SelectMenu() {
        initComponents();
        //Double amount = Double.parseDouble(Amount);
        loadRadioBtn();
        loadImg();
        setStock();
    }
    
    public SelectMenu(String Amount){
        initComponents();

    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Img2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        Img3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Img6 = new javax.swing.JLabel();
        Img7 = new javax.swing.JLabel();
        Img5 = new javax.swing.JLabel();
        Img4 = new javax.swing.JLabel();
        Img9 = new javax.swing.JLabel();
        Img1 = new javax.swing.JLabel();
        Img10 = new javax.swing.JLabel();
        Img8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1090, 860));
        setPreferredSize(new java.awt.Dimension(1090, 860));
        setResizable(false);
        getContentPane().setLayout(null);

        Img2.setBackground(new java.awt.Color(255, 204, 204));
        Img2.setForeground(new java.awt.Color(255, 255, 255));
        Img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img2.setMaximumSize(new java.awt.Dimension(120, 120));
        Img2.setMinimumSize(new java.awt.Dimension(120, 120));
        Img2.setOpaque(true);
        getContentPane().add(Img2);
        Img2.setBounds(250, 130, 174, 222);

        jButton10.setBackground(new java.awt.Color(204, 255, 204));
        jButton10.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton10.setText("jButton5");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(880, 680, 174, 49);

        Img3.setBackground(new java.awt.Color(255, 204, 204));
        Img3.setForeground(new java.awt.Color(255, 255, 255));
        Img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img3.setMaximumSize(new java.awt.Dimension(120, 120));
        Img3.setMinimumSize(new java.awt.Dimension(120, 120));
        Img3.setOpaque(true);
        getContentPane().add(Img3);
        Img3.setBounds(460, 130, 174, 222);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Select Drink:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 1090, 50);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 370, 174, 49);

        jButton11.setBackground(new java.awt.Color(255, 153, 153));
        jButton11.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jButton11.setText("Cancel");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(880, 750, 174, 49);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 370, 174, 49);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 370, 174, 49);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 370, 174, 49);

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(880, 370, 174, 49);

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(30, 680, 174, 49);

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(250, 680, 174, 49);

        Img6.setBackground(new java.awt.Color(255, 204, 204));
        Img6.setForeground(new java.awt.Color(255, 255, 255));
        Img6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img6.setMaximumSize(new java.awt.Dimension(120, 120));
        Img6.setMinimumSize(new java.awt.Dimension(120, 120));
        Img6.setOpaque(true);
        getContentPane().add(Img6);
        Img6.setBounds(30, 440, 174, 222);

        Img7.setBackground(new java.awt.Color(255, 204, 204));
        Img7.setForeground(new java.awt.Color(255, 255, 255));
        Img7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img7.setMaximumSize(new java.awt.Dimension(120, 120));
        Img7.setMinimumSize(new java.awt.Dimension(120, 120));
        Img7.setOpaque(true);
        getContentPane().add(Img7);
        Img7.setBounds(250, 440, 174, 222);

        Img5.setBackground(new java.awt.Color(255, 204, 204));
        Img5.setForeground(new java.awt.Color(255, 255, 255));
        Img5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img5.setMaximumSize(new java.awt.Dimension(120, 120));
        Img5.setMinimumSize(new java.awt.Dimension(120, 120));
        Img5.setOpaque(true);
        getContentPane().add(Img5);
        Img5.setBounds(880, 130, 174, 222);

        Img4.setBackground(new java.awt.Color(255, 204, 204));
        Img4.setForeground(new java.awt.Color(255, 255, 255));
        Img4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img4.setMaximumSize(new java.awt.Dimension(120, 120));
        Img4.setMinimumSize(new java.awt.Dimension(120, 120));
        Img4.setOpaque(true);
        getContentPane().add(Img4);
        Img4.setBounds(670, 130, 174, 222);

        Img9.setBackground(new java.awt.Color(255, 204, 204));
        Img9.setForeground(new java.awt.Color(255, 255, 255));
        Img9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img9.setMaximumSize(new java.awt.Dimension(120, 120));
        Img9.setMinimumSize(new java.awt.Dimension(120, 120));
        Img9.setOpaque(true);
        getContentPane().add(Img9);
        Img9.setBounds(670, 440, 174, 222);

        Img1.setBackground(new java.awt.Color(255, 204, 204));
        Img1.setForeground(new java.awt.Color(255, 255, 255));
        Img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img1.setLabelFor(Img1);
        Img1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img1.setMaximumSize(new java.awt.Dimension(120, 120));
        Img1.setMinimumSize(new java.awt.Dimension(120, 120));
        Img1.setOpaque(true);
        getContentPane().add(Img1);
        Img1.setBounds(30, 130, 174, 222);

        Img10.setBackground(new java.awt.Color(255, 204, 204));
        Img10.setForeground(new java.awt.Color(255, 255, 255));
        Img10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img10.setMaximumSize(new java.awt.Dimension(120, 120));
        Img10.setMinimumSize(new java.awt.Dimension(120, 120));
        Img10.setOpaque(true);
        getContentPane().add(Img10);
        Img10.setBounds(880, 440, 174, 222);

        Img8.setBackground(new java.awt.Color(255, 204, 204));
        Img8.setForeground(new java.awt.Color(255, 255, 255));
        Img8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Img8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Img8.setMaximumSize(new java.awt.Dimension(120, 120));
        Img8.setMinimumSize(new java.awt.Dimension(120, 120));
        Img8.setOpaque(true);
        getContentPane().add(Img8);
        Img8.setBounds(460, 440, 174, 222);

        jButton8.setBackground(new java.awt.Color(204, 255, 204));
        jButton8.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton8.setText("jButton3");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(460, 680, 174, 49);

        jButton9.setBackground(new java.awt.Color(204, 255, 204));
        jButton9.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton9.setText("jButton4");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(670, 680, 174, 49);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingmachine2/fbbe282e940039a76cb2d4216de7a914.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1090, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        //cancel process
        dispose();
        new DonePayment().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed
//Here if click button, it will get the price of button text and pass as parameter in payment method
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Payment(jButton10.getText());

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Payment(jButton9.getText());

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Payment(jButton8.getText());

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Payment(jButton7.getText());

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Payment(jButton6.getText());
 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Payment(jButton5.getText());

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Payment(jButton4.getText());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Payment(jButton3.getText());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Payment(jButton2.getText());

        //System.out.println(price);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Payment(jButton1.getText());


    }//GEN-LAST:event_jButton1ActionPerformed
   //Here end
    
    public void loadImg(){
        //load each drinks image to the label
        Img1.setIcon(setImg(jButton1.getText()));
        Img2.setIcon(setImg(jButton2.getText()));
        Img3.setIcon(setImg(jButton3.getText()));
        Img4.setIcon(setImg(jButton4.getText()));
        Img5.setIcon(setImg(jButton5.getText()));
        Img6.setIcon(setImg(jButton6.getText()));
        Img7.setIcon(setImg(jButton7.getText()));
        Img8.setIcon(setImg(jButton8.getText()));
        Img9.setIcon(setImg(jButton9.getText()));
        Img10.setIcon(setImg(jButton10.getText()));
      //  System.out.println(jButton1.getText());
        
    }
    
     public void loadRadioBtn(){
         //load drinks name and price to button
        Drinks newDrinks = new Drinks();
        List<String> lstAll = Drinks.getAll();
        List<String> DrinkNameLst = new ArrayList();
        for (String elem : lstAll){

        String[] split = elem.split("\\|");
        String name = split[1];
        String price = split[5];
      //  String countStock = split[2];
      //  String ImgPath = split[6];
        String join = String.join(" ", split[1], "$"+ split[5]);
        DrinkNameLst.add(join);
        
        //setImage(split[6]);
        //ImageIcon iconProfile = setImage(split[6]);  
        }
        Object[] drinkname =  DrinkNameLst.toArray(); 
        //System.out.println(Arrays.toString(drinkname));
        String namearr = Arrays.toString(drinkname);
        int i;
        //System.out.println(Arrays.toString(namearr));
        for(i = 0; i < drinkname.length; ++i){
        String[] name = namearr.split(",");
        jButton1.setText(name[0].replaceFirst("\\[",""));
        jButton2.setText(name[1]);
        jButton3.setText(name[2]);
        jButton4.setText(name[3]);
        jButton5.setText(name[4]);
        jButton6.setText(name[5]);
        jButton7.setText(name[6]);
        jButton8.setText(name[7]);
        jButton9.setText(name[8]);
        jButton10.setText(name[9].replaceFirst("\\]",""));
        //   System.out.println(name[i]);
        }
     }

      
      public void setStock(){
          // if stock low, then button will be disable
        Boolean enough = countStock(jButton1.getText());
        Boolean enough2 = countStock(jButton2.getText());
        Boolean enough3 = countStock(jButton3.getText());
        Boolean enough4 = countStock(jButton4.getText());
        Boolean enough5 = countStock(jButton5.getText());
        Boolean enough6 = countStock(jButton6.getText());
        Boolean enough7 = countStock(jButton7.getText());
        Boolean enough8 = countStock(jButton8.getText());
        Boolean enough9 = countStock(jButton9.getText());
        Boolean enough10 = countStock(jButton10.getText()); 
        /*   if (enough ==false){jStock1.setEnabled(false);}
        if (enough2 ==false){jStock2.setEnabled(false);}*/
        Boolean check[] = {enough,enough2,enough3,enough4,enough5,enough6,enough7,enough8,enough9,enough10};
        for (Boolean i : check){
            if (check[0] == false){jButton1.setBackground(Color.RED);jButton1.setForeground(Color.WHITE);jButton1.setEnabled(false);}
            if (check[1] == false){jButton2.setBackground(Color.RED);jButton2.setForeground(Color.WHITE);jButton2.setEnabled(false);}
            if (check[2] == false){jButton3.setBackground(Color.RED);jButton3.setForeground(Color.WHITE);jButton3.setEnabled(false);}
            if (check[3] == false){jButton4.setBackground(Color.RED);jButton4.setForeground(Color.WHITE);jButton4.setEnabled(false);}
            if (check[4] == false){jButton5.setBackground(Color.RED);jButton5.setForeground(Color.WHITE);jButton5.setEnabled(false);}
            if (check[5] == false){jButton6.setBackground(Color.RED);jButton6.setForeground(Color.WHITE);jButton6.setEnabled(false);}
            if (check[6] == false){jButton7.setBackground(Color.RED);jButton7.setForeground(Color.WHITE);jButton7.setEnabled(false);}
            if (check[7] == false){jButton8.setBackground(Color.RED);jButton8.setForeground(Color.WHITE);jButton8.setEnabled(false);}
            if (check[8] == false){jButton9.setBackground(Color.RED);jButton9.setForeground(Color.WHITE);jButton9.setEnabled(false);}
            if (check[9] == false){jButton10.setBackground(Color.RED);jButton10.setForeground(Color.WHITE);jButton10.setEnabled(false);}

       // System.out.println(i);
        }        
    }
       public Boolean countStock(String drksname2){
           //check number of stock;
        Boolean enough = false;
     Drinks newDrinks = new Drinks();
        List<String> lstAll = Drinks.getAll();
        List<String> DrinkNameLst = new ArrayList();
        double price = 0;
        for (String elem : lstAll){
        //filter the bottle drinks records
        //String drksname2 = "Pepsi $2.5"; 
        String drksname = removePrice(drksname2); 
        String[] split = elem.split("\\|");
        if (split[1].equalsIgnoreCase(drksname.trim()) && Integer.parseInt(split[2]) > 0){
            enough = true;
          }// System.out.println(drksname + " " + enough);      
        }
       
        return enough; 
    }
       
         public String removePrice(String name2){
             //remove price from the button text
        //countStock(drksname);  
        String name = name2;
        int seperator = name.lastIndexOf("$");
        String drksname = name.substring(0, seperator);
         //System.out.println(name2);
        return drksname;
       
     
    }
        
    public double checkprice(String drksname){
        //check price of selected drinks
        Drinks newDrinks = new Drinks();
        List<String> lstAll = Drinks.getAll();
        List<String> DrinkNameLst = new ArrayList();
        double price = 0;
        for (String elem : lstAll){
        //filter the bottle drinks records
      
        
        String[] split = elem.split("\\|");
        if (split[1].equalsIgnoreCase(drksname.trim())){
            price = Double.parseDouble(split[5]);
            break;
          //  System.out.println(drksname + " " + price);
          }
       // System.out.println( Double.parseDouble(split[5]));
        }
        System.out.println(drksname + " " + price);
        return price; 
    }   
    
    public void Payment(String Name){
        //open payment frame with passing value
        String name = removePrice(Name);
        Drinks newDrinks = new Drinks();
        double price = checkprice(name);
        Double TotalPrice = price;
        new Payment(TotalPrice,Name).setVisible(true);
        dispose();
    }
              
     public ImageIcon setImg(String name){
         //get image path
        //Boolean enough = false;
        ImageIcon iconPicture = null;
        Drinks newDrinks = new Drinks();
        List<String> lstAll = Drinks.getAll();
        List<String> DrinkNameLst = new ArrayList();
        //double price = 0;
        
        for (String elem : lstAll){
        String[] split = elem.split("\\|");
        String name2 = removePrice(name);
       // System.out.println(split[1]);
        if (split[1].equalsIgnoreCase(name2.trim())){
            String filepath = split[6];
            iconPicture = new ImageIcon(split[6]);
            System.out.println(filepath);
             //  jImg.setIcon(iconProfile);
             Image image = iconPicture.getImage();
             image = image.getScaledInstance(150,150,Image.SCALE_SMOOTH);
             iconPicture = new ImageIcon(image);
             //Img1.setIcon(iconPicture);
          }  
        }
       
       return iconPicture; 
     }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Img1;
    private javax.swing.JLabel Img10;
    private javax.swing.JLabel Img2;
    private javax.swing.JLabel Img3;
    private javax.swing.JLabel Img4;
    private javax.swing.JLabel Img5;
    private javax.swing.JLabel Img6;
    private javax.swing.JLabel Img7;
    private javax.swing.JLabel Img8;
    private javax.swing.JLabel Img9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
